const DB_KEY="medisafeBD_final_v1", PATIENT_SESSION="medisafe_patient_session", DOCTOR_SESSION="medisafe_doctor_session";
function today(){return new Date().toISOString().slice(0,10)}
function seedDB(){
 let db=JSON.parse(localStorage.getItem(DB_KEY)||"null");
 if(db)return db;
 db={patients:[{id:"MSBD-P-10001",name:"Demo Patient",nid:"NID-10001",birthRegistration:"BR-10001",temporaryId:"NB-10001",age:22,gender:"Female",bloodGroup:"B+",allergy:"Penicillin",problem:"",medical:[{date:"2026-09-01",condition:"Fever / respiratory infection",doctor:"Dr. Rahman",notes:"Initial consultation."},{date:"2026-09-20",condition:"General check-up",doctor:"Dr. Hasan",notes:"Follow-up."}],antibiotics:[{date:"2026-09-01",medicine:"Amoxicillin",reason:"Respiratory infection",course:"5 days",status:"Completed"}],prescriptions:[{date:"2026-09-20",doctor:"Dr. Hasan",medicine:"Paracetamol",dose:"500 mg when needed",instruction:"Use according to doctor advice.",antibiotic:false}],reports:[{date:"2026-09-01",name:"CBC",file:"Demo report"},{date:"2026-09-02",name:"Chest X-Ray",file:"Demo report"}]}],doctors:[{name:"Dr. Rahman",bmdc:"BMDC-1001",password:"demo123",specialty:"Medicine"},{name:"Dr. Hasan",bmdc:"BMDC-1002",password:"demo123",specialty:"ENT"}]};localStorage.setItem(DB_KEY,JSON.stringify(db));return db}
function getDB(){return seedDB()} function saveDB(db){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function patientSession(){return JSON.parse(sessionStorage.getItem(PATIENT_SESSION)||"null")}
function doctorSession(){return JSON.parse(sessionStorage.getItem(DOCTOR_SESSION)||"null")}
document.addEventListener("DOMContentLoaded",()=>{seedDB();const pf=document.getElementById("patientLoginForm");if(pf)pf.onsubmit=patientLoginSubmit;const df=document.getElementById("doctorLoginForm");if(df)df.onsubmit=doctorLoginSubmit;if(document.getElementById("patientInfo"))renderPatient();if(document.getElementById("doctorPatientInfo"))renderDoctor()})
function patientLoginSubmit(e){e.preventDefault();const db=getDB(),id=document.getElementById("patientId").value.trim(),name=document.getElementById("patientName").value.trim(),type=document.getElementById("verificationType").value,val=document.getElementById("verificationValue").value.trim();const p=db.patients.find(x=>x.id===id&&x.name.toLowerCase()===name.toLowerCase());if(!p||p[type]!==val){alert("Patient information বা verification মিলছে না। Demo login: Demo Patient / MSBD-P-10001 / NID-10001");return}sessionStorage.setItem(PATIENT_SESSION,JSON.stringify({id:p.id}));location.href="patient-portal.html"}
function doctorLoginSubmit(e){e.preventDefault();const db=getDB(),name=document.getElementById("doctorName").value.trim(),b=document.getElementById("doctorBMDC").value.trim(),pw=document.getElementById("doctorPassword").value;const d=db.doctors.find(x=>x.name.toLowerCase()===name.toLowerCase()&&x.bmdc===b&&x.password===pw);if(!d){alert("Doctor credentials মিলছে না। Demo: Dr. Rahman / BMDC-1001 / demo123");return}sessionStorage.setItem(DOCTOR_SESSION,JSON.stringify({bmdc:d.bmdc,name:d.name}));location.href="doctor-portal.html"}
function patientLogout(){sessionStorage.removeItem(PATIENT_SESSION);location.href="index.html"} function doctorLogout(){sessionStorage.removeItem(DOCTOR_SESSION);location.href="../index.html"}
function currentPatient(){const s=patientSession();return s?getDB().patients.find(p=>p.id===s.id):null}
function showSection(id){["dashboard","problem","medical","antibiotic","prescription","reports","specialist"].forEach(x=>document.getElementById(x)?.classList.toggle("hidden",x!==id))}
function renderPatient(){const p=currentPatient();if(!p){location.href="patient-login.html";return}document.getElementById("welcome").textContent="👤 Welcome, "+p.name;document.getElementById("patientInfo").innerHTML=`<p><b>Patient ID:</b> ${esc(p.id)}<br><b>Age:</b> ${p.age}<br><b>Gender:</b> ${esc(p.gender)}<br><b>Blood Group:</b> ${esc(p.bloodGroup)}<br><b>Allergy:</b> ${esc(p.allergy)}</p>`;document.getElementById("problemText").value=p.problem||"";document.getElementById("visitCount").textContent=p.medical.length;document.getElementById("abxCount").textContent=p.antibiotics.length;document.getElementById("rxCount").textContent=p.prescriptions.length;document.getElementById("reportCount").textContent=p.reports.length;document.getElementById("medicalBody").innerHTML=p.medical.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.condition)}</td><td>${esc(x.doctor)}</td><td>${esc(x.notes)}</td></tr>`).join("");document.getElementById("antibioticBody").innerHTML=p.antibiotics.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.medicine)}</td><td>${esc(x.reason)}</td><td>${esc(x.course)}</td><td>${esc(x.status)}</td></tr>`).join("");document.getElementById("prescriptionList").innerHTML=p.prescriptions.map(x=>`<div class="mini-card"><b>${esc(x.medicine)}</b><br>${esc(x.dose)}<br>${esc(x.instruction)}<br><small>${esc(x.date)} — ${esc(x.doctor)}</small></div>`).join("");renderPatientReports();document.getElementById("patientAlert").textContent=p.allergy?`Safety notice: recorded allergy — ${p.allergy}. Doctors should review this before prescribing.`:"No recorded allergy."}
function savePatientProblem(){const p=currentPatient();if(!p)return;p.problem=document.getElementById("problemText").value.trim();const db=getDB(),i=db.patients.findIndex(x=>x.id===p.id);db.patients[i]=p;saveDB(db);alert("Health problem saved. Your doctor can view it.");renderPatient()}
function addPatientReport(){const p=currentPatient();if(!p)return;const name=document.getElementById("reportName").value.trim();if(!name){alert("Report name দিন।");return}p.reports.push({date:document.getElementById("reportDate").value||today(),name,file:document.getElementById("reportFile").files[0]?.name||"Uploaded demo report"});const db=getDB();db.patients[db.patients.findIndex(x=>x.id===p.id)]=p;saveDB(db);renderPatient();alert("Test report added.");}
function renderPatientReports(){const p=currentPatient();document.getElementById("reportList").innerHTML=p.reports.map(x=>`<div class="mini-card"><b>${esc(x.name)}</b> — ${esc(x.date)}<br>${esc(x.file)}</div>`).join("")}
function suggestSpecialist(){const p=currentPatient(),t=(p?.problem||"").toLowerCase();let s="General Medicine";if(/ear|nose|throat|কান|নাক|গলা/.test(t))s="ENT";else if(/skin|rash|চুল|ত্বক/.test(t))s="Dermatology";else if(/eye|চোখ/.test(t))s="Ophthalmology";document.getElementById("specialistResult").innerHTML=`সম্ভাব্য specialist category: <b>${s}</b><br>এটি informational guidance, diagnosis নয়।`}
function doctorSection(id){["dashboard","search","medical","antibiotic","reports","problem","prescription"].forEach(x=>document.getElementById(x)?.classList.toggle("hidden",x!==id));renderDoctor()}
function selectedDoctorPatient(){return JSON.parse(sessionStorage.getItem("selectedDoctorPatient")||"null")}
function searchPatient(){const q=document.getElementById("patientSearch").value.trim().toLowerCase(),p=getDB().patients.find(x=>x.id.toLowerCase()===q||x.name.toLowerCase().includes(q));if(!p){document.getElementById("searchResult").innerHTML='<div class="alert danger">Patient not found.</div>';return}sessionStorage.setItem("selectedDoctorPatient",JSON.stringify({id:p.id}));renderDoctor();document.getElementById("searchResult").innerHTML=`<div class="mini-card"><b>${esc(p.name)}</b><br>${esc(p.id)}<br><button class="btn" onclick="doctorSection('medical')">Open Complete History</button></div>`}
function doctorPatient(){const s=selectedDoctorPatient();return s?getDB().patients.find(p=>p.id===s.id):getDB().patients[0]}
function renderDoctor(){const p=doctorPatient();if(!p)return;document.getElementById("doctorPatientInfo").innerHTML=`<div class="mini-card"><b>${esc(p.name)}</b> | ${esc(p.id)} | Blood: ${esc(p.bloodGroup)} | Allergy: ${esc(p.allergy)}</div>`;document.getElementById("dMedicalBody").innerHTML=p.medical.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.condition)}</td><td>${esc(x.doctor)}</td><td>${esc(x.notes)}</td></tr>`).join("");document.getElementById("dAbxBody").innerHTML=p.antibiotics.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.medicine)}</td><td>${esc(x.reason)}</td><td>${esc(x.course)}</td><td>${esc(x.status)}</td></tr>`).join("");document.getElementById("doctorReports").innerHTML=p.reports.map(x=>`<div class="mini-card"><b>${esc(x.name)}</b> — ${esc(x.date)}<br>${esc(x.file)}</div>`).join("");document.getElementById("doctorProblem").innerHTML=p.problem?esc(p.problem):"Patient has not entered a health problem yet.";document.getElementById("dMedicalCount").textContent=p.medical.length;document.getElementById("dAbxCount").textContent=p.antibiotics.length}
function addMedicalRecord(){const p=doctorPatient(),d=doctorSession();if(!d)return;const condition=document.getElementById("mCondition").value.trim();if(!condition){alert("Condition দিন।");return}p.medical.push({date:document.getElementById("mDate").value||today(),condition,doctor:d.name,notes:document.getElementById("mNotes").value.trim()});const db=getDB();db.patients[db.patients.findIndex(x=>x.id===p.id)]=p;saveDB(db);renderDoctor();alert("Medical record added.");}
function savePrescription(){const p=doctorPatient(),d=doctorSession();if(!d)return;const medicine=document.getElementById("rxMedicine").value.trim(),dose=document.getElementById("rxDose").value.trim(),instruction=document.getElementById("rxInstruction").value.trim(),isAbx=document.getElementById("isAntibiotic").checked,reason=document.getElementById("rxReason").value.trim();if(!medicine){alert("Medicine name দিন।");return}const danger=isAbx&&/amoxicillin/i.test(medicine)&&/penicillin/i.test(p.allergy||"");if(danger){document.getElementById("safetyResult").innerHTML='<div class="alert danger"><b>⚠ Antibiotic Resistance & Prescription Safety Alert</b><br>Recorded Penicillin allergy conflicts with Amoxicillin. Prescription blocked.</div>';return}p.prescriptions.push({date:today(),doctor:d.name,medicine,dose,instruction,antibiotic:isAbx});if(isAbx)p.antibiotics.push({date:today(),medicine,reason,course:"As prescribed",status:"Active"});const db=getDB();db.patients[db.patients.findIndex(x=>x.id===p.id)]=p;saveDB(db);document.getElementById("safetyResult").innerHTML='<div class="alert">Prescription saved after safety check.</div>';renderDoctor()}
